export const INITIAL_REGION = {
  latitude: 38.672085700614446,
  longitude: 21.590127479285,
  latitudeDelta: 5.863403880667256,
};

const COLOR_THEME = {
  delian: "teal",
  delianHQ: "navy",
  peloponnesian: "tomato",
  peloponnesianHQ: "red",
  neutral: "gold",
};

export const CITIES = [
  {
    latlng: {
      latitude: 37.081944,
      longitude: 22.423611,
    },
    name: "Sparta",
    description: "Peloponnesian League HQ",
    color: COLOR_THEME.peloponnesianHQ,
  },
  {
    latlng: {
      latitude: 37.905346,
      longitude: 22.880192,
    },
    name: "Corinth",
    description: "Peloponnesian League",
    color: COLOR_THEME.peloponnesian,
  },
  {
    latlng: {
      latitude: 37.89131,
      longitude: 21.37493,
    },
    name: "Elis",
    description: "Peloponnesian League",
    color: COLOR_THEME.peloponnesian,
  },
  {
    latlng: {
      latitude: 37.996389,
      longitude: 23.344444,
    },
    name: "Megara",
    description: "Peloponnesian League",
    color: COLOR_THEME.peloponnesian,
  },
  {
    latlng: {
      latitude: 38.316667,
      longitude: 23.316667,
    },
    name: "Thebes",
    description: "Dominant power in Boeotia",
    color: COLOR_THEME.peloponnesian,
  },
  {
    latlng: {
      latitude: 37.97,
      longitude: 23.72,
    },
    name: "Athens",
    description: "Delian League HQ",
    color: COLOR_THEME.delianHQ,
  },
  {
    latlng: {
      latitude: 37.943,
      longitude: 23.646944,
    },
    name: "Piraeus",
    description: "Port city of Athens",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 37.393333,
      longitude: 25.271111,
    },
    name: "Delos",
    description: "Delian League Treasury",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 37.0875,
      longitude: 25.403889,
    },
    name: "Naxos",
    description: "Delian League",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 38.4,
      longitude: 26.016667,
    },
    name: "Chios",
    description: "Delian League",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 39.21,
      longitude: 26.28,
    },
    name: "Lesbos",
    description: "Delian League",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 37.75,
      longitude: 26.833333,
    },
    name: "Samos",
    description: "Delian League",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 39.583333,
      longitude: 19.866667,
    },
    name: "Corcyra",
    description: "Delian League",
    color: COLOR_THEME.delian,
  },
  {
    latlng: {
      latitude: 37.616667,
      longitude: 22.716667,
    },
    name: "Argos",
    description: "Neutral",
    color: COLOR_THEME.neutral,
  },
  {
    latlng: {
      latitude: 36.683333,
      longitude: 24.416667,
    },
    name: "Melos",
    description: "Neutral",
    color: COLOR_THEME.neutral,
  },
];

export const BATTLES = [
  {
    latlng: {
      latitude: 39.4033333,
      longitude: 20.2152778,
    },
    name: "Battle of Sybota",
    year: -433,
    location: "Off Corcyra",
    type: "naval",
    result: "Stalemate, both Corinth and Corcyra claimed victory",
    color: COLOR_THEME.neutral,
    link: "https://en.wikipedia.org/wiki/Battle_of_Sybota",
  },
  {
    latlng: {
      latitude: 40.1937,
      longitude: 23.3278,
    },
    name: "Battle of Potidaea",
    year: -432,
    location: "Potidaea",
    type: "siege",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Potidaea",
  },
  {
    latlng: {
      latitude: 40.2832,
      longitude: 23.2954,
    },
    name: "Battle of Spartolos",
    year: -429,
    location: "Chalcidice",
    type: "land",
    result: "Chalcidian victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Spartolos",
  },
  {
    latlng: {
      latitude: 38.3,
      longitude: 21.783333,
    },
    name: "Battle of Rhium",
    year: -429,
    location: "Mouth of the Corinthian Gulf, near present-day Rio, Greece",
    type: "naval",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Rhium",
  },
  {
    latlng: {
      latitude: 38.393889,
      longitude: 21.830556,
    },
    name: "Battle of Naupactus",
    year: -429,
    location: "Off Naupactus",
    type: "naval",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Naupactus",
  },
  {
    latlng: {
      latitude: 38.219992,
      longitude: 23.273853,
    },
    name: "Siege of Plataea",
    year: -429,
    endYear: -427,
    location: "Plataea",
    type: "siege",
    result: "Theban victory, Plataea razed to the ground",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Siege_of_Plataea",
  },
  {
    latlng: {
      latitude: 39.21,
      longitude: 26.28,
    },
    name: "Mytilenean revolt",
    year: -428,
    endYear: -427,
    location: "Lesbos",
    type: "revolt",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Mytilenean_revolt",
  },
  {
    latlng: {
      latitude: 38.316667,
      longitude: 23.533333,
    },
    name: "Battle of Tanagra",
    year: -426,
    location: "Tanagra",
    type: "land",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Tanagra_(426_BC)",
  },
  {
    latlng: {
      latitude: 38.5054294,
      longitude: 21.8091625,
    },
    name: "Aetolian campaign",
    year: -426,
    location: "Aetolia",
    type: "land",
    result: "Aetolian victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Aetolian_campaign",
  },
  {
    latlng: {
      latitude: 38.949996,
      longitude: 21.149835,
    },
    name: "Battle of Olpae",
    year: -426,
    location: "Olpae",
    type: "land",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Olpae",
  },
  {
    latlng: {
      latitude: 38.85,
      longitude: 21.166667,
    },
    name: "Battle of Idomene",
    year: -426,
    location: "Idomene",
    type: "land",
    result: "Athenian Victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Idomene",
  },
  {
    latlng: {
      latitude: 36.916667,
      longitude: 21.7,
    },
    name: "Battle of Pylos",
    year: -425,
    location: "Pylos",
    type: "land",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Pylos",
  },
  {
    latlng: {
      latitude: 36.930136,
      longitude: 21.665725,
    },
    name: "Battle of Sphacteria",
    year: -425,
    location: "Sphacteria, a small island at the entrance to the bay of Pylos",
    type: "land",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Sphacteria",
  },
  {
    latlng: {
      latitude: 37.996389,
      longitude: 23.344444,
    },
    name: "Battle of Megara",
    year: -424,
    location: "Megara, Greece",
    type: "land",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Megara",
  },
  {
    latlng: {
      latitude: 38.346208,
      longitude: 23.661354,
    },
    name: "Battle of Delium",
    year: -424,
    location: "Delium",
    type: "land",
    result: "Boeotian victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Delium",
  },
  {
    latlng: {
      latitude: 40.818333,
      longitude: 23.84,
    },
    name: "Battle of Amphipolis",
    year: -422,
    location: "Amphipolis",
    type: "land",
    result: "Decisive Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Amphipolis",
  },
  {
    latlng: {
      latitude: 37.617642,
      longitude: 22.392869,
    },
    name: "Battle of Mantinea",
    year: -418,
    location: "Mantinea",
    type: "land",
    result: "Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Mantinea_(418_BC)",
  },
  {
    latlng: {
      latitude: 37.519836,
      longitude: 22.585884,
    },
    name: "Battle of Hysiae",
    year: -417,
    location: "Hysiae, Argolis",
    type: "siege",
    result: "Decisive Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Hysiae_(417_BC)",
  },
  {
    latlng: {
      latitude: 37.713973,
      longitude: 22.557292,
    },
    name: "Battle of Orneae",
    year: -417,
    location: "Orneae, Argolis",
    type: "siege",
    result: "Athenian/Argive Victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Orneae",
  },
  {
    latlng: {
      latitude: 36.683333,
      longitude: 24.416667,
    },
    name: "Siege of Melos",
    year: -416,
    location: "Melos",
    type: "siege",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Siege_of_Melos",
  },
  {
    latlng: {
      latitude: 37.0833,
      longitude: 15.2833,
    },
    name: "Sicilian Expedition",
    year: -415,
    endYear: -413,
    location: "Sicily, Italy",
    type: "land",
    result:
      "Decisive Spartan/Syracusan victory, Athenian expeditionary force completely destroyed",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Sicilian_Expedition",
  },
  {
    latlng: {
      latitude: 36.583333,
      longitude: 27.833333,
    },
    name: "Battle of Syme",
    year: -411,
    month: 8,
    location: "Off Syme",
    type: "naval",
    result: "Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Syme",
  },
  {
    latlng: {
      latitude: 38.3927202,
      longitude: 23.7930669,
    },
    name: "Battle of Eretria",
    year: -411,
    month: 8,
    location: "Off the coast of Euboea",
    type: "naval",
    result: "Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Eretria",
  },
  {
    latlng: {
      latitude: 40.148611,
      longitude: 26.379167,
    },
    name: "Battle of Cynossema",
    year: -411,
    location: "Off Cynossema, in the Thracian Chersonese",
    type: "naval",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Cynossema",
  },
  {
    latlng: {
      latitude: 40.195278,
      longitude: 26.405,
    },
    name: "Battle of Abydos",
    year: -411,
    month: 10,
    location: "Near Abydos, in the Hellespont",
    type: "naval",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Abydos",
  },
  {
    latlng: {
      latitude: 40.38,
      longitude: 27.89,
    },
    name: "Battle of Cyzicus",
    year: -410,
    location: "Near Cyzicus, Hellespont, modern-day Turkey",
    type: "naval",
    result:
      "Decisive Athenian victory, Cyzicus and other cities in the region captured by Athens",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Cyzicus",
  },
  {
    latlng: {
      latitude: 37.992778,
      longitude: 26.8475,
    },
    name: "Battle of Notium",
    year: -406,
    location: "Near Ephesus and Notium",
    type: "naval",
    result: "Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Notium",
  },
  {
    latlng: {
      latitude: 39.1,
      longitude: 26.55,
    },
    name: "Battle of Mytilene",
    year: -406,
    location: "Mytilene",
    type: "naval",
    result: "Spartan victory",
    color: COLOR_THEME.peloponnesian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Mytilene_(406_BC)",
  },
  {
    latlng: {
      latitude: 39.033333,
      longitude: 26.8,
    },
    name: "Battle of Arginusae",
    year: -406,
    location: "Arginusae Islands",
    type: "naval",
    result: "Athenian victory",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Arginusae",
  },
  {
    latlng: {
      latitude: 40.25,
      longitude: 26.55,
    },
    name: "Battle of Aegospotami",
    year: -405,
    location:
      "Aegospotami, Hellespont (present-day Çanakkale Province, Turkey)",
    type: "naval",
    result:
      "Decisive Spartan victory: - Athens besieged and then surrendered in March 404 BC, ending the Peloponnesian War",
    color: COLOR_THEME.delian,
    link: "https://en.wikipedia.org/wiki/Battle_of_Aegospotami",
  },
];
